name: 'GitHub Actions for SwiftLint'
description: 'A tool to enforce Swift style and conventions'
author: 'Jaehong Kang <sinoru@me.com>'
branding:
  icon: 'shield'
  color: 'orange'
inputs:
  swiftlint-version:
    description: "A SwiftLint version to use."
    required: true
    default: '0.47.1'
  working-directory:
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        echo "{SWIFTLINT_PATH}={${{ github.action_path }}/SwiftLint}" >> $GITHUB_ENV
        echo "{SWIFTLINT_PACKAGE_ARGS}={--package-path '${{ github.action_path }}/SwiftLint' -c release --manifest-cache local}"
      shell: bash
    - uses: actions/checkout@v3
      with: 
        repository: 'realm/SwiftLint'
        ref: '${{ inputs.swiftlint-version }}'
        path: '${{ github.env.SWIFTLINT_PATH }}'
    - uses: actions/cache@v3
      with:
        path: '${{ github.env.SWIFTLINT_PATH }}/.build'
        key: swiftlint-${{ runner.os }}-spm-${{ inputs.swiftlint-version }}-${{ hashFiles('${{ github.env.SWIFTLINT_PATH }}/Package.*') }}
        restore-keys: |
          ${{ runner.os }}-spm-${{ inputs.swiftlint-version }}-
    - run: swift build $SWIFTLINT_PACKAGE_ARGS
      shell: bash
    - run: swiftlint.sh
      shell: bash
      working-directory: '${{ github.workspace }}/${{ inputs.working-directory }}'
