name: Tests

on:
  push:
    paths: 
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'swiftlint.sh'
  pull_request:
    paths: 
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'swiftlint.sh'

jobs:
  test-errors:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sinoru/actions-setup-swift@main
        with:
          swift-version: '5.6.1'
      - uses: .
        with:
          working-directory: test/errors
  
  test-no-lintable-files:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sinoru/actions-setup-swift@main
        with:
          swift-version: '5.6.1'
      - uses: .
        with:
          working-directory: test/no-lintable-files

  test-Warnings:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sinoru/actions-setup-swift@main
        with:
          swift-version: '5.6.1'
      - uses: .
        with:
          working-directory: test/Warnings
